### ISSUE TITLE
Feature Request: Custom Prefixes/Suffixes

### ISSUE THREAD

**Issue by theinit01** [randomusernameapi/randomusernameapi.github.io#1]
Allow users to provide their own prefixes or suffixes. You could add optional query parameters like prefix and suffix.
Example: GET https://usernameapiv1.vercel.app/api/random-usernames?prefix=Cool&suffix=Gamer

**Comment by theinit01** [comment]
@linuxfandudeguy Can I work on this issue?

**Comment by linuxfandudeguy** [comment]
Unfortunately can't do this because there is no GitHub repo where the API is hosted there is only the Github repo where this GitHub pages website is hosted, i am very sorry that I couldn't do this
